inherit_from: ./.rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'

Style/StringLiterals:  
  EnforcedStyle: double_quotes