inherit_from:
  - .rubocop_todo.yml
  - ./.rubocop_todo.yml


require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'vendor/**/*'

Style/StringLiterals:  
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 100